package cmd

// TestNoULIDDemo is the acceptance proof for known-zv1.3.
//
// Scenario: an agent adds two knowledge entries and creates a link between them
// using only human-readable content queries — no ULIDs appear anywhere in the
// agent-issued commands.
//
// This mirrors the Mode 4 failure from the friction audit: the agent regex'd
// `"id":[0-9]*` on JSON output, got empty (ULIDs don't match), and stored a
// correction entry without linking it to the original. The fix: content-
// addressable resolution (resolveEntry) plus `link accept` with 1-based indices.

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/dpoage/known/model"
	"github.com/dpoage/known/query"
	"github.com/dpoage/known/storage"
)

func TestNoULIDDemo(t *testing.T) {
	ctx := context.Background()

	// --- setup: in-memory DB + stub engine (no real embedder needed) ----------
	db, err := newBackend(ctx, ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err := db.Migrate(); err != nil {
		t.Fatal(err)
	}

	stub := &demoEmbedder{}
	eng := query.New(db.Entries(), db.Edges(), stub)

	var buf bytes.Buffer
	app := &App{
		DB:      db,
		Entries: db.Entries(),
		Edges:   db.Edges(),
		Engine:  eng,
		Printer: NewPrinter(&buf, false, false),
		Stderr:  &bytes.Buffer{},
		Config:  &AppConfig{DefaultScope: model.RootScope},
	}

	// --- step 1: agent stores two entries (no ULIDs) -------------------------
	//
	// The agent uses plain content strings. Internally these become ULIDs, but
	// the agent never sees or types them.

	src := model.Source{Type: model.SourceManual}

	original := model.NewEntry("Renderer architecture decision: 3D will be a sibling renderer", src)
	original.Scope = model.RootScope
	original = original.WithEmbedding([]float32{1, 0, 0, 0}, "demo")
	storedOriginal, err := app.Entries.CreateOrUpdate(ctx, &original)
	if err != nil {
		t.Fatal(err)
	}

	correction := model.NewEntry("CORRECTION: renderer will be a plugin, not a sibling renderer", src)
	correction.Scope = model.RootScope
	correction = correction.WithEmbedding([]float32{0.95, 0.31, 0, 0}, "demo")
	storedCorrection, err := app.Entries.CreateOrUpdate(ctx, &correction)
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("original ID:   %s (agent never types this)", storedOriginal.ID)
	t.Logf("correction ID: %s (agent never types this)", storedCorrection.ID)

	// Confirm no ULIDs were typed in the agent commands above.
	// The agent used only content strings; IDs were generated by the store.

	// --- step 2: agent links via content query — zero ULIDs typed ------------
	//
	// "known link 'renderer architecture decision' 'CORRECTION: renderer'"
	// Both args are content queries, resolved by text search.
	err = runLink(ctx, app, []string{
		"renderer architecture decision",
		"CORRECTION: renderer will be a plugin",
	})
	if err != nil {
		t.Fatalf("content-query link failed: %v", err)
	}

	// Verify the edge was created.
	edges, err := app.Edges.EdgesFrom(ctx, storedOriginal.ID, storage.EdgeFilter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(edges) == 0 {
		t.Fatal("expected at least one edge from original → correction")
	}
	if edges[0].ToID != storedCorrection.ID {
		t.Errorf("edge target: got %s, want %s", edges[0].ToID, storedCorrection.ID)
	}

	// --- step 3: agent accepts suggestions via 1-based index — zero ULIDs ----
	//
	// "known link accept 'renderer architecture decision' 1"
	//
	// Add a third entry and accept it as a suggestion without typing any ULID.
	related := model.NewEntry("Graphics pipeline initialization sequence", src)
	related.Scope = model.RootScope
	related = related.WithEmbedding([]float32{0.85, 0.526, 0, 0}, "demo")
	if _, err := app.Entries.CreateOrUpdate(ctx, &related); err != nil {
		t.Fatal(err)
	}

	// The agent says: "known link accept 'renderer architecture' 1"
	// No ULID appears in this command.
	err = runLinkAccept(ctx, app, []string{
		"renderer architecture",
		"1",
	})
	if err != nil {
		t.Fatalf("link accept failed: %v", err)
	}

	// Verify a second edge was created from the original.
	allEdges, err := app.Edges.EdgesFrom(ctx, storedOriginal.ID, storage.EdgeFilter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(allEdges) < 2 {
		t.Errorf("expected 2 edges after accept, got %d", len(allEdges))
	}

	// --- invariant: no ULID appears in any agent-issued command string --------
	agentCommands := []string{
		"renderer architecture decision",
		"CORRECTION: renderer will be a plugin",
		"renderer architecture",
		"1",
	}
	for _, cmd := range agentCommands {
		if looksLikeULID(cmd) {
			t.Errorf("agent command contains what looks like a ULID: %q", cmd)
		}
	}

	output := buf.String()
	t.Logf("output:\n%s", output)
}

// looksLikeULID returns true if s looks like a 26-character Crockford base32
// ULID (all uppercase alphanumeric, no hyphens).
func looksLikeULID(s string) bool {
	s = strings.TrimSpace(s)
	if len(s) != 26 {
		return false
	}
	const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
	for _, c := range s {
		if !strings.ContainsRune(crockford, c) {
			return false
		}
	}
	return true
}

// demoEmbedder returns zero vectors. SuggestLinks uses the stored embedding
// vectors directly (SearchSimilar on the repo), so the embedder is only
// consulted for text-based resolution fallback.
type demoEmbedder struct{}

func (d *demoEmbedder) Embed(_ context.Context, _ string) ([]float32, error) {
	return []float32{0, 0, 0, 0}, nil
}
func (d *demoEmbedder) EmbedBatch(_ context.Context, texts []string) ([][]float32, error) {
	out := make([][]float32, len(texts))
	for i := range out {
		out[i] = []float32{0, 0, 0, 0}
	}
	return out, nil
}
func (d *demoEmbedder) Dimensions() int  { return 4 }
func (d *demoEmbedder) ModelName() string { return "demo" }
